{% set name = "google-cloud-audit-log" %}
{% set version = "0.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-audit-log-{{ version }}.tar.gz
  sha256: 6d89903848aee9817477ece306544851b903a5ec561da966bbba5a8d12509a4d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4
    - googleapis-common-protos >=1.52.0
    - protobuf >=3.6.0

test:
  imports:
    - google.cloud.audit.audit_log_pb2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-audit-log
  summary: Google Cloud Audit Protos
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://github.com/googleapis/python-audit-log
  dev_url: https://github.com/googleapis/python-audit-log

extra:
  recipe-maintainers:
    - xylar
